### PR TITLE
Microverse HTML and CSS - New York Times Clone

### PR DESCRIPTION
**Pull request by rootDEV2990**
This is our clone of the New Your Times page [https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0](url) please help us review so we may continue improving. Thanks!

### CODE REVIEW

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes 🔴

Hi @rootDEV2990 and @Maclenn77 your project looks great. 👍 **Congratulations** on a great job. Before we approve your project, we have to fix the following comments:
- The new your times' logo is a link, currently, it is not a link. Let us fix it.
ab
- The nav should have a fixed position. It should stick at the top
ab1
- The footer should have a fixed position.
ab2
- Let us fix the positioning of the elements of the footer to look like the original. Currently, this is how it looks like
abfooter
```Original version```
abfooter1

Kindly make these changes and submit another code review 🙂 
_Happy coding_ 👨‍💻 
@slack on Daniel Larbi Addo

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Great work @rootDEV2990 and @Maclenn77!
You have done an amazing job building this and incorporating the changes requested by my colleague. However, there are a few things left to resolve. Please see my comments below, make the appropriate changes and request your next review!

#### Navigation
Your navigation bar seems to be a little buggy, for instance the buttons in the right section of the navbar are overflowing beyond the browser window, please give this a second look.

#### Sections are too narrow
Please consider looking into the 'More in space and astronomy section as well as the footer, comparing these sections with those on the original page, you may find that yours are a bit too narrow as the ones on the original page are basically full-width.

Please consider these few comments, make the appropriate changes and request another review! I wish you the very best and see you at the top :rocket: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Review by addod19 — APPROVED** [review]
## Status: Approved 🏆 🎈 

Hi, **Team** congratulations for making all the changes and making the project beautiful. 👍 You can now merge to master and submit the project completion form. 😄 Great work !!

Good luck with your next projects 😃 
_Happy coding_ 👨‍💻 
@slack on **Daniel Larbi Addo**

**Comment by addod19** [comment]
Hi Team, it is a late [OPTIONAL] feedback if forgot. The header has shifted under the nav. Let us increase the margin-top so we have some space at the header nicely. Thank you 😄

**Pull request merged**
